version: '3'

services:
  angular: 
    build: ng4-client
    volumes: 
      - ./ng4-client:/ng-app 
    ports:
      - "4200:4200"

  server: 
    build: server 
    ports:
      - "3000:3000" 
    links: 
      - database  

  database: 
    image: mongo 
    ports:
      - "27017:27017" 

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    links: 
      - angular
